#!/bin/bash

# The script will outline the commands necessary to perform a FastViromeExplorer job.
# There are two dependencies which FastViromeExplorer uses: kallisto and samtools.
# Make sure that the two depedencies are installed and exist within your $PATH environment.

# Purge existing modules
module purge

# Load java module for running FastViromeExplorer
module load jdk/1.8.0

# TODO:
# - Setup command line arguments so qsub knows which input file to use
#   - Use -F flag to specify arguments for job
# - Run the java command for FastViromeExplorer
#   - java -cp bin FastViromeExplorer -1 $FILE_1 -2 $FILE_2 -i $INDEX_FILE -o $OUTPUT_DIR
# - ssh to arc login node
# - send curl request to /api/job_finished for job completion notification
#   - The parameters should include the job id and the location path of the output file 
#   - curl $URL/api/jobs/finished/$JOB_ID -X POST
