#!/bin/bash

# Arguments:
# 1. input read path
# 2. index path
# 3. output path
# 4. arc username
# 5. genome length path

# The script will outline the commands necessary to perform a FastViromeExplorer job.
# There are two dependencies which FastViromeExplorer uses: kallisto and samtools.
# Make sure that the two depedencies are installed and exist within your $PATH environment.

# Purge existing modules.
module purge

# Load java module for running FastViromeExplorer.
module load jdk/1.8.0

# Copy the java binaries to $WORK for fast I/O operations.
cp -r $HOME/FastViromeExplorer/bin $WORK

ssh $5@newriver1.arc.vt.edu \
    "curl https://7f6c927c.ngrok.io/api/jobs/started/$3 -X POST"

java -cp $WORK/bin FastViromeExplorer \
    -1 $HOME/$1 \
    -i $HOME/FastViromeExplorer/$2 \
    -l $HOME/FastViromeExplorer/$5 \
    -o $HOME/$3

# ssh to the login node to send a request to the node server that the job is complete.
# TODO: the curl url should be replaced with the production url.
ssh $4@newriver1.arc.vt.edu \
    "curl https://7f6c927c.ngrok.io/api/jobs/finished/$3 -X POST"

cd $HOME/$3
mv FastViromeExplorer-final-sorted-abundance.tsv output_$3.tsv
mv FastViromeExplorer-reads-mapped-sorted.sam output_$3.sam
tar -zcvf output.tar.gz output_$3.tsv output_$3.sam
tar -zcvf abundance.tar.gz output_$3.tsv