#!/bin/bash

# Arguments:
# There are five arguments for the job:
# 1. input read path
# 2. input read path
# 3. index path
# 4. output path
# 5. arc username

# The script will outline the commands necessary to perform a FastViromeExplorer job.
# There are two dependencies which FastViromeExplorer uses: kallisto and samtools.
# Make sure that the two depedencies are installed and exist within your $PATH environment.

# Purge existing modules.
module purge

# Load java module for running FastViromeExplorer.
module load jdk/1.8.0

# Copy the java binaries to $WORK for fast I/O operations.
cp -r $HOME/FastViromeExplorer/bin $WORK

java -cp $WORK/bin FastViromeExplorer \
    -1 $HOME/$1 \
    -2 $HOME/$2 \
    -i $HOME/$3 -o $4

# ssh to the login node to send a request to the node server that the job is complete.
# TODO: the curl url should be replaced with the production url.
ssh $5@newriver1.arc.vt.edu \
    "curl https://7f6c927c.ngrok.io/api/jobs/finished/$4 -X POST"